// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/VladimirStepanov/todo-app/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MailService is an autogenerated mock type for the MailService type
type MailService struct {
	mock.Mock
}

// SendConfirmationsEmail provides a mock function with given fields: user
func (_m *MailService) SendConfirmationsEmail(user *models.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
