version: "3.7"

volumes:
  todo-db-data:

services:
    todo_db:
        image: postgres:latest
        env_file: ../.env
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - todo-db-data:/var/lib/postgresql/data
        expose:
            - "${POSTGRES_PORT}"
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        command: -p ${POSTGRES_PORT}
    
    tokendb:
        env_file: ../.env
        image: "redis:alpine"
        command: --port ${REDIS_PORT}
        ports:
            - "${REDIS_PORT}:${REDIS_PORT}"
    
    todo:
        env_file: ../.env
        depends_on: 
            - todo_db
        build:
            context: ./
            dockerfile: Dockerfile-prod
        volumes:
            - ./../:/app
        ports:
            - "${APP_PORT}:${APP_PORT}"
        entrypoint: sh scripts/start.sh