name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  testing:
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: todo
          POSTGRES_USER: test        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Unit tests
        run: go test -short -v ./...
      
      - name: Integration tests
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: todo
          POSTGRES_USER: test
          POSTGRES_PORT: 5432
          POSTGRES_HOST: postgresql
          REDIS_HOST: redis
          REDIS_PORT: 6379
          CGO_ENABLED: 0
        run: | 
          go run cmd/migrate/migrate.go -direction up
          go run cmd/migrate/migrate.go -direction up
          go test -v ./it